server {
  listen 8080;
  root /usr/share/nginx/html;

  gzip on;
  gzip_types application/javascript text/css application/wasm application/json;

  location / {
    try_files $uri $uri/ /index.html;
  }
}